# Generated by Django 2.2.5 on 2019-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
