# Generated by Django 2.2.5 on 2019-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='filed',
            field=models.BooleanField(default=False),
        ),
    ]
