# Generated by Django 2.2.5 on 2019-09-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_task_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
